### ISSUE TITLE
code JS for first page

### ISSUE THREAD

**Issue by bretaj** [bretaj/bootcampProject1#3]

**Comment by bretaj** [comment]
### Subtasks
- [ ] Subtask 1: create script so "total products by category" is imported from local storage once modal form is submitted
- [ ] Subtask 1a: product category is listed in alphabetical order
- [ ] Subtask 1b: number of product is displayed next to product name
- [ ] Subtask 2: create script so modal appears when "add inventory" is clicked
- [ ] Subtask 3: create script so "order soon" is imported from local storage once modal form is submitted
- [ ] Subtask 4:
