### ISSUE TITLE
style first page using CSS framework

### ISSUE THREAD

**Issue by bretaj** [bretaj/bootcampProject1#5]

**Comment by bretaj** [comment]
### Subtasks
- [ ] Subtask 1: Description of task
- [ ] Subtask 2: Description of task
- [ ] Subtask 3: Description of task
